# Generated by Django 4.1 on 2024-10-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='time',
        ),
        migrations.AddField(
            model_name='notice',
            name='interval',
            field=models.PositiveIntegerField(default=1, help_text='Interval in seconds'),
            preserve_default=False,
        ),
    ]
